# Generated by Django 3.1.2 on 2020-10-05 20:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_album_album_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_logo',
        ),
    ]
