# Generated by Django 3.1.2 on 2020-10-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_remove_album_album_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='album_logo',
            field=models.CharField(default=None, max_length=250),
        ),
        migrations.AddField(
            model_name='album',
            name='album_logoo',
            field=models.CharField(default=None, max_length=250),
        ),
    ]
