# Generated by Django 3.1.2 on 2020-10-05 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_auto_20201005_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='album_logo',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='album',
            name='album_logoo',
            field=models.CharField(max_length=250),
        ),
    ]
