# Generated by Django 3.1.2 on 2020-10-05 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0006_auto_20201005_2033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='album_logoo',
        ),
    ]
